// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRdihcEWTrSjFZm4sSt9xvO4aNFAhNrA',
    appId: '1:778018924973:web:50cad8fca670eedd9f1924',
    messagingSenderId: '778018924973',
    projectId: 'cacekkes-4e066',
    authDomain: 'cacekkes-4e066.firebaseapp.com',
    storageBucket: 'cacekkes-4e066.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCTZZYJclLphNed-PWBEZbh434w4f3n0',
    appId: '1:778018924973:android:28d7502834b7f5c79f1924',
    messagingSenderId: '778018924973',
    projectId: 'cacekkes-4e066',
    storageBucket: 'cacekkes-4e066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-r4nS0QAgZ06uUPq8cC-NDS672QKJJA',
    appId: '1:778018924973:ios:bdd54238281550779f1924',
    messagingSenderId: '778018924973',
    projectId: 'cacekkes-4e066',
    storageBucket: 'cacekkes-4e066.appspot.com',
    iosClientId: '778018924973-40ru7iggd3umkjrjnp2ddgrofnl7lpv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cacekkes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-r4nS0QAgZ06uUPq8cC-NDS672QKJJA',
    appId: '1:778018924973:ios:bdd54238281550779f1924',
    messagingSenderId: '778018924973',
    projectId: 'cacekkes-4e066',
    storageBucket: 'cacekkes-4e066.appspot.com',
    iosClientId: '778018924973-40ru7iggd3umkjrjnp2ddgrofnl7lpv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cacekkes',
  );
}
